services:
  db:
    image: postgres:18
    container_name: atatek_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    networks:
      - atatek_line
    # 👇 Новый рекомендуемый путь маунта
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - atatek_line

  redis:
    image: redis:latest
    container_name: atatek_redis
    ports:
      - "6379:6379"
    networks:
      - atatek_line
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atatek_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - atatek_line
    environment:
      - APP_VERSION=4.0.0
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/app

networks:
  atatek_line:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
