"""set null

Revision ID: 0a97ee2ae4c4
Revises: df98c6635b40
Create Date: 2025-10-24 19:07:53.940251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a97ee2ae4c4'
down_revision: Union[str, Sequence[str], None] = 'df98c6635b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_address_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_address_id_fkey'), 'users', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
