"""fix table

Revision ID: 69a1b845c707
Revises: 7990285c89d6
Create Date: 2025-10-22 17:09:10.361640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a1b845c707'
down_revision: Union[str, Sequence[str], None] = '7990285c89d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tree', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'tree', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tree', type_='foreignkey')
    op.drop_constraint(None, 'tree', type_='foreignkey')
    # ### end Alembic commands ###
