"""set null

Revision ID: df98c6635b40
Revises: 69a1b845c707
Create Date: 2025-10-24 19:07:42.464436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df98c6635b40'
down_revision: Union[str, Sequence[str], None] = '69a1b845c707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_page_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'pages', ['page_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_page_id_fkey'), 'users', 'pages', ['page_id'], ['id'])
    # ### end Alembic commands ###
